# Generated by Django 2.1.7 on 2019-03-28 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_uf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('municipio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Município')),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('ddd', models.CharField(max_length=2, verbose_name='DDD')),
                ('telefone', models.CharField(blank=True, help_text='XXXXX-XXXX', max_length=9, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, help_text='XXXXX-XXXX', max_length=9, null=True, verbose_name='Celular')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='Home Page da Empresa')),
                ('email', models.EmailField(blank=True, help_text='Apenas se a empresa tiver um email central', max_length=254, null=True, verbose_name='E-Mail da Empresa')),
                ('VP_Nome', models.CharField(max_length=100, verbose_name='VP ou Diretor da Empresa')),
                ('VP_Cargo', models.CharField(max_length=60, verbose_name='Cargo VP ou Diretor')),
                ('VP_Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('VP_DDD', models.CharField(max_length=2, verbose_name='DDD')),
                ('VP_Telefone', models.CharField(blank=True, help_text='XXXXX-XXXX', max_length=9, null=True, verbose_name='Celular')),
                ('C1_Nome', models.CharField(max_length=100, verbose_name='VP ou Diretor da Empresa')),
                ('C1_Cargo', models.CharField(max_length=60, verbose_name='Cargo VP ou Diretor')),
                ('C1_Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('C1_DDD', models.CharField(max_length=2, verbose_name='DDD')),
                ('C1_Telefone', models.CharField(blank=True, help_text='XXXXX-XXXX', max_length=9, null=True, verbose_name='Celular')),
                ('C2_Nome', models.CharField(max_length=100, verbose_name='VP ou Diretor da Empresa')),
                ('C2_Cargo', models.CharField(max_length=60, verbose_name='Cargo VP ou Diretor')),
                ('C2_Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('C2_DDD', models.CharField(max_length=2, verbose_name='DDD')),
                ('C2_Telefone', models.CharField(blank=True, help_text='XXXXX-XXXX', max_length=9, null=True, verbose_name='Celular')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Area')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Regional')),
                ('uf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.UF')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaAgencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=40)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricao.Empresa')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.UF')),
            ],
            options={
                'verbose_name': 'Agência',
                'verbose_name_plural': 'Agências',
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtinclusao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricao.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricao.Usuario'),
        ),
    ]
