# Generated by Django 2.1.7 on 2019-04-02 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_regional_estados'),
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='Seq')),
                ('titulo', models.CharField(max_length=60)),
                ('parcerias', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(blank=True, max_length=60, null=True)),
                ('produto', models.CharField(blank=True, max_length=30, null=True)),
                ('dtinicio', models.DateField(verbose_name='Veiculação ou Início')),
                ('isolada', models.BooleanField(default=False)),
                ('DiretorCriacao', models.CharField(blank=True, max_length=100, null=True)),
                ('Planejamento', models.CharField(blank=True, max_length=100, null=True)),
                ('Redacao', models.CharField(blank=True, max_length=140, null=True)),
                ('DiretorArte', models.CharField(blank=True, max_length=140, null=True)),
                ('ProducaoGrafica', models.CharField(blank=True, max_length=80, null=True)),
                ('ProducaoRTVC', models.CharField(blank=True, max_length=80, null=True)),
                ('TecnologiaDigital', models.CharField(blank=True, max_length=80, null=True)),
                ('OutrosAgencia1', models.CharField(blank=True, max_length=80, null=True)),
                ('OutrosAgencia2', models.CharField(blank=True, max_length=80, null=True)),
                ('Midia', models.CharField(blank=True, max_length=60, null=True)),
                ('Atendimento', models.CharField(blank=True, max_length=80, null=True)),
                ('Aprovacao', models.CharField(blank=True, max_length=100, null=True)),
                ('ProdutoraFilme', models.CharField(blank=True, max_length=50, null=True)),
                ('DiretorFilme', models.CharField(blank=True, max_length=50, null=True)),
                ('ProdutoraAudio', models.CharField(blank=True, max_length=50, null=True)),
                ('DiretorAudio', models.CharField(blank=True, max_length=50, null=True)),
                ('EstudioFotografia', models.CharField(blank=True, max_length=40, null=True)),
                ('Fotografo', models.CharField(blank=True, max_length=50, null=True)),
                ('EstudioIlustracao', models.CharField(blank=True, max_length=40, null=True)),
                ('Ilustrador', models.CharField(blank=True, max_length=50, null=True)),
                ('ManipulacaoDigital', models.CharField(blank=True, max_length=40, null=True)),
                ('Finalizacao', models.CharField(blank=True, max_length=40, null=True)),
                ('OutrosFornecedor1', models.CharField(blank=True, max_length=80, null=True)),
                ('OutrosFornecedor2', models.CharField(blank=True, max_length=80, null=True)),
                ('roteiro', models.TextField(blank=True, null=True, verbose_name='Roteiro de Rádio')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.EmpresaAgencia')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.Empresa')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Formato')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Premio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.Usuario')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('idsoundcloud', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricao.Inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.TipoMaterial'),
        ),
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['usuario', 'empresa', 'seq'], name='inscricao_i_usuario_2e5192_idx'),
        ),
    ]
