# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_auto_20190402_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomaterial',
            options={'verbose_name': 'Tipo de Material', 'verbose_name_plural': 'Tipos de Materiais'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='C1_Cargo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cargo VP ou Diretor'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='C1_DDD',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='C1_Nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VP ou Diretor da Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='C2_Cargo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cargo VP ou Diretor'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='C2_DDD',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='C2_Nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VP ou Diretor da Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Area', verbose_name='Área'),
        ),
    ]
