# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='DiretorArte',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Diretor de Arte'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ProducaoGrafica',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Produção Gráfica'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ProducaoRTVC',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Produção RTVC'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Redacao',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Redação'),
        ),
    ]
