# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0006_auto_20190420_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='OutrosAgencia3',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=80, null=True, verbose_name='Outros Créditos'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='OutrosAgencia4',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=80, null=True, verbose_name='Outros Créditos'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='OutrosFornecedor3',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=80, null=True, verbose_name='Outros Créditos de Fornecedores'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='OutrosFornecedor4',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=80, null=True, verbose_name='Outros Créditos de Fornecedores'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='celular',
            field=models.CharField(blank=True, help_text='XXXXX-XXXX', max_length=10, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, help_text='XXXXX-XXXX', max_length=10, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Aprovacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aprovação'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Atendimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atendimento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='DiretorAudio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Diretor de Áudio'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='DiretorCriacao',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=100, null=True, verbose_name='Diretor de Criação'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='DiretorFilme',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Diretor do Filme'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='EstudioFotografia',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Estúdio de Fotografia'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='EstudioIlustracao',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Estúdio de Ilustração'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Finalizacao',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Finalização'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Fotografo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fotógrafo'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ManipulacaoDigital',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Manipulação Digital'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Midia',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Mídia'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='OutrosAgencia1',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=80, null=True, verbose_name='Outros Créditos'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='OutrosAgencia2',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=80, null=True, verbose_name='Outros Créditos'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='OutrosFornecedor1',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=80, null=True, verbose_name='Outros Créditos de Fornecedores'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='OutrosFornecedor2',
            field=models.CharField(blank=True, help_text='Utilize o formato: "Função, Fulano, Beltrano e Sicrano', max_length=80, null=True, verbose_name='Outros Créditos de Fornecedores'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Planejamento',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Planejamento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ProdutoraAudio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Produtora de Áudio'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ProdutoraFilme',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Produtora do Filme'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='TecnologiaDigital',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Tecnologia Digital'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
    ]
