# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0007_auto_20190620_2330'),
        ('inscricao', '0007_auto_20190621_0852'),
    ]

    operations = [
    ]
