# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0008_merge_20190621_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Atendimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atendimento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Midia',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Mídia'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Planejamento',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Planejamento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Formato'),
        ),
    ]
