# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0009_auto_20190629_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaagencia',
            name='agencia',
            field=models.CharField(max_length=40, verbose_name='Nome da Agência'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='agencia',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.Empresa'), chained_model_field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.Empresa'), on_delete=django.db.models.deletion.CASCADE, to='inscricao.EmpresaAgencia'),
        ),
    ]
