# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0012_auto_20191226_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='roteiro',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='dtexportacao',
            field=models.DateField(blank=True, null=True, verbose_name='Dt.Exportação'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='dtinclusao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Dt.Inclusão'),
        ),
    ]
