# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0013_auto_20191230_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('A', 'Em edição'), ('V', 'Validada')], default='A', max_length=1),
        ),
    ]
