# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-20 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0014_inscricao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='agencia',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='empresa', chained_model_field='empresa', on_delete=django.db.models.deletion.CASCADE, to='inscricao.EmpresaAgencia', verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='premiacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Premiacao', verbose_name='Premiação'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='titulo',
            field=models.CharField(max_length=60, verbose_name='Título'),
        ),
    ]
