# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0015_auto_20200120_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='premio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Premio'),
        ),
    ]
