# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import inscricao.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0016_auto_20200122_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=inscricao.models.path),
        ),
    ]
