# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0018_auto_20200130_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('tipo', 'id'), 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('A', 'Em aberto'), ('F', 'Finalizado')], default='A', max_length=1, verbose_name='Situação'),
        ),
    ]
