# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0019_auto_20200214_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalizadas',
            fields=[
                ('empresa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inscricao.Empresa')),
            ],
            bases=('inscricao.empresa',),
        ),
    ]
