# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0019_auto_20200214_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dtexportacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt.Exportação'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dtfinalizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt.Finalização'),
        ),
    ]
