# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-29 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0020_finalizadas'),
        ('inscricao', '0020_auto_20200229_1253'),
    ]

    operations = [
    ]
