# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-13 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0021_merge_20200229_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finalizadas',
        ),
    ]
