# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0022_auto_20200313_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalizadas',
            fields=[
            ],
            options={
                'verbose_name': 'Finalizada',
                'verbose_name_plural': 'Finalizadas',
                'proxy': True,
                'indexes': [],
            },
            bases=('inscricao.empresa',),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='preco_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Preço Calculado'),
        ),
    ]
