# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0023_auto_20200314_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalizadas',
            options={'verbose_name': 'Inscrição Finalizada', 'verbose_name_plural': 'Inscrições Finalizadas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes', verbose_name='Comprovante de Depósito'),
        ),
    ]
