# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(blank=True, through='cms.SectionItem', to='cms.Section'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='article',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'section', chained_model_field=b'sections', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Article', verbose_name='Artigo'),
        ),
        migrations.AlterField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(blank=True, through='cms.SectionItem', to='cms.Article'),
        ),
    ]
