# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160921_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='path',
            field=models.FilePathField(editable=False, max_length=256, path=b'/home/josir/bitbucket/ongportal/ongportal/media/uploads/themes', recursive=True),
        ),
    ]
