# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160928_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='path',
            field=models.FilePathField(editable=False, max_length=256, path=b'/media/leonardo/BACKUP/Workspace/radix/ongportal/ongportal/ongportal/media/uploads/themes', recursive=True),
        ),
    ]
