# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20160930_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='path',
            field=models.FilePathField(editable=False, max_length=256, path=b'/home/josir/bitbucket/ongportal/ongportal/media/uploads/themes', recursive=True),
        ),
    ]
