# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-28 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20190126_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='recurso',
            field=models.CharField(choices=[('EMAIL', 'Envio de email autom\xe1tico'), ('SITE_NAME', 'Nome do Site'), ('ROBOTS', 'Permite busca pelo Google'), ('COMMENT_P', 'Texto para coment\xe1rios privados'), ('COMMENT', 'Texto para coment\xe1rios'), ('SIGNUP', 'Permite cadastro de usu\xe1rios'), ('EMAILADMIN', 'Quem recebe avisos de novos usu\xe1rios'), ('CP_ANUAL', 'C\xf3digo do Plano Anual'), ('CP_PLUS', 'C\xf3digo do Plano Plus')], max_length=10, unique=True, verbose_name='Par\xe2metro'),
        ),
    ]
