# Generated by Django 2.1.7 on 2019-03-24 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20190216_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.CharField(choices=[('A', 'Permite comentários'), ('P', 'Permite comentários privados'), ('F', 'Fechado para novos comentários'), ('N', 'Sem comentários')], default='N', max_length=1, verbose_name='Comentários'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='articlearchive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='emailagendado',
            name='status',
            field=models.CharField(choices=[('A', 'Aguardando envio manual...'), ('S', 'Enviando...'), ('R', 'Re-enviando'), ('E', 'Erro ao enviar'), ('K', 'Enviado')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='emailagendado',
            name='subject',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Article'),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='create_article',
            field=models.BooleanField(default=False, verbose_name='Criação do Artigo'),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='file',
            field=models.FileField(upload_to='uploads', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='article',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='section', chained_model_field='sections', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Article', verbose_name='Artigo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cms.Menu', verbose_name='Pai'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.Section', verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='path',
            field=models.FilePathField(editable=False, max_length=256, path='/home/josir/bitbucket/colunistas/colunistas/media/uploads/themes', recursive=True),
        ),
        migrations.AlterField(
            model_name='urlmigrate',
            name='redirect_type',
            field=models.CharField(choices=[('M', 'MOVED'), ('H', 'HOTLINK')], max_length=1, verbose_name='Tipo'),
        ),
    ]
