# Generated by Django 2.2.6 on 2019-10-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Sobrenome')),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
        ),
    ]
