# Generated by Django 2.2.6 on 2019-10-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_pessoa_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('numero', models.IntegerField()),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
            ],
        ),
    ]
