# Generated by Django 2.1.7 on 2019-03-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premiacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=3)),
                ('ordem', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Premiações',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterModelOptions(
            name='premio',
            options={'ordering': ('ano',), 'verbose_name': 'Premio', 'verbose_name_plural': 'Premios'},
        ),
        migrations.RemoveField(
            model_name='premio',
            name='nome',
        ),
        migrations.AddField(
            model_name='premio',
            name='ano',
            field=models.SmallIntegerField(default=2010),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premio',
            name='regional',
            field=models.ForeignKey(default=1,on_delete=django.db.models.deletion.PROTECT, to='base.Regional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premio',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto para Inscrições'), ('F', 'Inscrições encerradas'), ('C', 'Concluído')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premio',
            name='premiacao',
            field=models.ForeignKey(default=1,on_delete=django.db.models.deletion.PROTECT, to='base.Premiacao'),
            preserve_default=False,
        ),
    ]
