# Generated by Django 2.1.7 on 2019-03-27 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190324_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('descricao', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=3)),
                ('cod_premiacao', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='premiacao',
            options={'ordering': ('nome',), 'verbose_name': 'Premiação', 'verbose_name_plural': 'Premiações'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(default='A', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formato',
            name='premiacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Premiacao'),
        ),
    ]
