# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_regional_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='regional',
            name='codigo',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
    ]
