# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_regional_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('arquivo', models.BooleanField(default=False)),
                ('url', models.BooleanField(default=False)),
                ('roteiro', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Materiais',
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('descricao',), 'verbose_name': 'Área de Atuação', 'verbose_name_plural': 'Áreas de Atuação'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('codigo',)},
        ),
        migrations.AlterModelOptions(
            name='formato',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='premiacao',
            options={'ordering': ('ordem',), 'verbose_name': 'Premiação', 'verbose_name_plural': 'Premiações'},
        ),
        migrations.AlterModelOptions(
            name='uf',
            options={'ordering': ('sigla',)},
        ),
        migrations.AlterField(
            model_name='premio',
            name='ano',
            field=models.SmallIntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='premiacao',
            name='materiais',
            field=models.ManyToManyField(to='base.TipoMaterial'),
        ),
    ]
