# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190420_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('descricao',), 'verbose_name': 'Área de Atividade', 'verbose_name_plural': 'Áreas de Atividade'},
        ),
        migrations.AlterModelOptions(
            name='tipomaterial',
            options={'ordering': ('descricao',), 'verbose_name': 'Tipo de Material', 'verbose_name_plural': 'Tipos de Materiais'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(max_length=6, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(verbose_name='Texto explicativo'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='ano',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='premio',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto para Inscrições'), ('F', 'Inscrições encerradas'), ('C', 'Concluído')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='regional',
            name='codigo',
            field=models.CharField(max_length=2, verbose_name='Código'),
        ),
    ]
