# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190420_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='premiacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Premiacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premio',
            name='ano',
            field=models.SmallIntegerField(default=2019),
        ),
    ]
