# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190420_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uf',
            options={'ordering': ('sigla',), 'verbose_name': 'UF', 'verbose_name_plural': 'Unidades da Federação'},
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='arquivo',
            field=models.BooleanField(default=False, verbose_name='Permite anexar arquivo'),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='descricao',
            field=models.CharField(max_length=40, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='roteiro',
            field=models.BooleanField(default=False, verbose_name='Permite registro de roteiros'),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='url',
            field=models.BooleanField(default=False, verbose_name='Permite URL'),
        ),
    ]
