# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190621_0852'),
        ('base', '0011_auto_20190620_2330'),
    ]

    operations = [
    ]
