# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_merge_20190621_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='premiacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Premiacao', verbose_name='Premiação'),
        ),
    ]
