# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20190629_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='premiacao',
        ),
        migrations.AlterField(
            model_name='premio',
            name='ano',
            field=models.SmallIntegerField(),
        ),
    ]
