# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20200123_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomaterial',
            name='dicas',
            field=models.TextField(blank=True, null=True, verbose_name='Dicas para preenchimento'),
        ),
    ]
