# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20200130_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiacao',
            name='URLApoio',
            field=models.URLField(blank=True, null=True, verbose_name='URL Apoio'),
        ),
    ]
