# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_premiacao_urlapoio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Preço Regular')),
                ('preco_serie', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Preço para Série')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Categoria')),
                ('premiacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Premiacao', verbose_name='Premiação')),
            ],
            options={
                'verbose_name': 'Preço',
                'ordering': ('premiacao', 'categoria'),
            },
        ),
    ]
