# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-13 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='preco',
            name='contabiliza_materiais',
            field=models.BooleanField(default=False, verbose_name='Contabiliza Materiais'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='categoria',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='premiacao', chained_model_field='premiacao', help_text='Deixe em branco para o caso geral', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Categoria'),
        ),
    ]
